# Use tall and fullscreen layouts
layouts:
  - 'tall'
  - 'fullscreen'
  - 'two-pane'
  - '3column-right'

# Modifer Key
mod1:
  - option
  - shift

mod2:
  - option
  - shift
  - control

# Allow windows to float
floating:
  - 'com.apple.systempreferences'
  - 'com.toggl.daneel'
  - 'at.obdev.littlesnitch'

# Mouse, for now
mouse-resizes-windows: true
mouse-swaps-windows: true
mouse-follows-focus: true
focus-follows-mouse: false

# Layout
enables-layout-hud: true

# Windows
float-small-windows: true
restore-layouts-on-launch: true
