echo "                   ..- - .               "
echo "                   '        \`.           "
echo "                  '.- .  .--. .          "
echo "                 |: _ | :  _ :|          "
echo "                 |\`(@)--\`.(@) |          "
echo "                 : .'     \`-, :          "
echo "                 :(_____.-'.' \`          "
echo "                 : \`-.__.-'   :          "
echo "                 \`  _.    _.   .         "
echo "                /  /  \`_ '  \    .       "
echo "               .  :          \\   \      "
echo "              .  : _      __  .\   .     "
echo "             .  /             : \`.  \    "
echo "            :  /      '        : \`.  .   "
echo "           '  \`      :          : :  \`.  "
echo "         .\`_ :       :          / '   |  "
echo "         :' \ .      :           '__  :  "
echo "      .--'   \\\`-._    .      .' :    \`).  "
echo "    ..|       \   )          :   '._.'  : "
echo "   ;           \-'.        ..:         / "
echo "   '.           \  - ....-   |        '  "
echo "      -.         :   _____   |      .'   "
echo "        \` -.    .'--       --\`.   .'     "
echo "            \`--                --        "
echo "Generic Linux Bootstrap"
