#!/bin/zsh
#
# I put all of my nnn config here. It is sourced in .zshrc
#
# Set cd on Quit
QUIT_ON_CD_SCRIPT="/opt/homebrew/Cellar/nnn/4.8/share/nnn/quitcd/quitcd.bash_zsh"
if [[ -f "$QUIT_ON_CD_SCRIPT" ]]; then
  source "$QUIT_ON_CD_SCRIPT"
fi

# Plugin install/update info: https://github.com/jarun/nnn/tree/master/plugins#installation
NNN_VISUAL='p:preview-tui'
NNN_TOOLS='o:nuke;n:bulknew;r:gitroot;d:diffs'
NNN_PROJ='v:! project'
NNN_SEARCH='s:fzcd;z:autojump'

export NNN_FIFO=/tmp/nnn.fifo
export NNN_PLUG="$NNN_VISUAL;$NNN_TOOLS;$NNN_SEARCH;$NNN_PROJ"
export NNN_OPTS='C'
