gui:
  mouseEvents: false
  showIcons: true
git:
  paging:
    colorArg: 'always'
    # Delta keeps causing crashes
    # pager: 'delta --dark --paging=never'
  # branchLogCmd: 'glol {{branchName}} --'
keybinding:
  universal:
    quit: '<C-c>'
    quit-alt1: '<C-q>'
    nextMatch: 'g'
    prevMatch: 't'
    redo: '<C-r>'
    undo: 'u'
